# config.py 
APP_ID = 'TU_APP_ID' 
APP_SECRET = 'TU_APP_SECRET' 
ACCESS_TOKEN = 'TU_TOKEN_PERMANENTE_DEL_USUARIO_DEL_SISTEMA' 
AD_ACCOUNT_ID = 'act_TU_ID_DE_CUENTA_PUBLICITARIA' # ¡Importante el prefijo 'act_'! 
